version: '3'

networks:
  local_network:
    external: true

services:
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - .env.production
    ports:
      - 9000:9000
    networks:
      - local_network
