http:
  port: ${PORT:-3000}
  host: ${HOST:-localhost}

admin:
  port: 9876
  host: localhost

apiEndpoints:
  presentationAPI:
    host: ${HOST:-localhost}
    paths: '/presentation/*'
    methods: 'GET,POST,PUT,PATCH,DELETE'

serviceEndpoints:
  presentationService:
    url: ${PRESENTATION_SERVICE_URL:-http://localhost:3001/}

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  presentation:
    apiEndpoints:
      - presentationAPI
    policies:
      - log:
        - action:
            message: '${req.method} ${req.originalUrl}'
      - proxy:
        - action:
            serviceEndpoint: presentationService
            changeOrigin: true
            # /presentation/ping => http://localhost:3001/ping
            prependPath: true
            ignorePath: false
            stripPath: true
