http:
  port: ${PORT:-3000}
  host: ${HOST:-localhost}

admin:
  port: 9876
  host: localhost

apiEndpoints:
  all:
    host: "*"
    paths: "*"
  # audienceAPIV1:
  #   host: '*'
  #   paths: ['/presentation/v1/audience', '/presentation/v1/audience/*']
  #   methods: 'GET,POST,PUT,PATCH,DELETE'
  # presentationAPIV1:
  #   host: '*'
  #   paths: ['/presentation', '/presentation/*']
  #   methods: 'GET,POST,PUT,PATCH,DELETE'

serviceEndpoints:
  presentationService:
    urls:
      - ${PRESENTATION_SERVICE_URL:-http://localhost:3001}

policies:
  - request-transformer
  - response-transformer
  - proxy
  - introspection
  - scope
  - request-logger
  - introspection-v2
  - rsa-signature-validation
  - body-parser

pipelines:
  logRequest:
    apiEndpoints:
      - all

    policies:
      - request-logger:
      - response-transformer:
        - action:
            headers:
              add:
                X-Powered-By: "'Name Later Cloud Gateway'"
  # audience:
  #   apiEndpoints:
  #     - audienceAPIV1
  #   policies:
  #     - body-parser:
  #     - rsa-signature-validation:
  #     - proxy:
  #       - action:
  #           serviceEndpoint: presentationService
  #           changeOrigin: true
  #           prependPath: true
  #           ignorePath: false
  #           stripPath: true
  # presentation:
  #   apiEndpoints:
  #     - presentationAPIV1
  #   policies:
  #     - introspection-v2:
  #     - scope:
  #       - action:
  #           scope: ${PRESENTATION_SERVICE_SCOPE}
  #     - proxy:
  #       - action:
  #           serviceEndpoint: presentationService
  #           changeOrigin: true
  #           prependPath: true
  #           ignorePath: false
  #           stripPath: true
