http:
  port: ${PORT:-3000}
  host: ${HOST:-localhost}

admin:
  port: 9876
  host: localhost

apiEndpoints:
  all:
    host: "*"
    paths: "*"
  presentationAPIV1:
    host: '*'
    paths: ['/presentation/v1', '/presentation/v1/*']
    methods: 'GET,POST,PUT,PATCH,DELETE'

serviceEndpoints:
  presentationService:
    urls:
      - ${PRESENTATION_SERVICE_URL:-http://localhost:3001}

policies:
  - request-transformer
  - response-transformer
  - proxy
  - introspection
  - scope
  - request-logger

pipelines:
  logRequest:
    apiEndpoints:
      - all

    policies:
      - request-logger:
        # - action:
      - response-transformer:
        - action:
            headers:
              add:
                X-Powered-By: "'Name Later Cloud Gateway'"
  presentation:
    apiEndpoints:
      - presentationAPIV1
    policies:
      - introspection:
        - action:
            requestTimeHeader: 'X-Request-Time'
            serviceSlug: 'X-Service-Slug'
      - scope:
        - action:
            scope: ${PRESENTATION_SERVICE_SCOPE}
      - proxy:
        - action:
            serviceEndpoint: presentationService
            changeOrigin: true
            # /presentation/ping => http://localhost:3001/ping
            prependPath: true
            ignorePath: false
            stripPath: true
